# These are supported funding model platforms
github: [priteshyadav444]
open_collective: taskeasy
patreon: priteshyadav444
ko_fi: priteshyadav444
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: # Replace with a single Liberapay username
issuehunt: priteshyadav444
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://priteshyadav444.in/']
 
